server:
  port: 8080
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.102:10000/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

spring:
  application:
    name: api-gateway


zuul:
  routes:
    order-service:
      path: /order/**
      serviceId: order-service
      stripPrefix: false
    product-service: /apigateway/product/**
  ignored-patterns: /*-service/**
    #处理http请求头为空的问题
  sensitive-headers: